"""
Lightweight inspector for *.full_report.json generated by scripts/inspect_pdf.py.

Usage examples (PowerShell):

  # podstawowy podgląd wszystkich bloków
  python scripts/inspect_blocks_report.py "ścieżka\do\pliku.full_report.json"

  # tylko bloki typu variant_body
  python scripts/inspect_blocks_report.py "plik.full_report.json" --label variant_body

  # tylko variant_body + prophylaxis, z dłuższym preview (400 znaków)
  python scripts/inspect_blocks_report.py "plik.full_report.json" -l variant_body -l prophylaxis --max-chars 400

"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List, Dict, Any


def load_report(path: Path) -> Dict[str, Any]:
    """Load JSON report file produced by scripts/inspect_pdf.py."""
    text = path.read_text(encoding="utf-8")
    return json.loads(text)


def print_summary(report: Dict[str, Any]) -> None:
    """Print a short global summary (top-level stats)."""
    print("=== GLOBAL SUMMARY ===")
    print(f"PDF: {report.get('pdf')}")
    print(f"Use real GPT: {report.get('use_real_gpt')}")
    print(f"Raw blocks: {report.get('num_blocks_raw')}")
    print(f"Semantic blocks: {report.get('num_semantic_blocks')}")
    print(f"Segments for aggregation: {report.get('num_segments_for_aggregation')}")

    label_counts = report.get("label_counts", {})
    print("Label counts (segment level):")
    for label, count in sorted(label_counts.items()):
        print(f"  - {label}: {count}")

    print()
    print("Variants (summary):")
    for v in report.get("variants", []):
        print(
            f"  {v['variant_id']}: "
            f"header={v['has_header']}, "
            f"body={v['num_body']}, "
            f"prophylaxis={v['num_prophylaxis']}, "
            f"header_preview={repr(v['header_preview'][:80]) if v['header_preview'] else None}"
        )
    print()


def print_blocks(
    report: Dict[str, Any],
    labels: List[str] | None = None,
    max_chars: int = 200,
) -> None:
    """
    Pretty-print semantic blocks + their classifications.

    :param labels: optional list of labels to include
                   (e.g. ["variant_header", "variant_body"])
    :param max_chars: max number of characters shown for block text preview
    """
    semantic_blocks = report.get("semantic_blocks", [])
    block_classes = report.get("block_classifications", [])

    if not semantic_blocks or not block_classes:
        print("No semantic_blocks or block_classifications in report.")
        return

    if len(semantic_blocks) != len(block_classes):
        print(
            f"WARNING: semantic_blocks ({len(semantic_blocks)}) and "
            f"block_classifications ({len(block_classes)}) length mismatch"
        )

    print("=== SEMANTIC BLOCKS ===")
    for idx, (blk, cls) in enumerate(zip(semantic_blocks, block_classes)):
        label = cls.get("label")
        if labels and label not in labels:
            continue

        page_start = blk.get("page_start")
        page_end = blk.get("page_end")
        block_id = blk.get("block_id")
        var_hint = cls.get("variant_hint")
        conf = cls.get("confidence", 0.0)
        type_hint = blk.get("type_hint")

        text = blk.get("text", "").replace("\n", " ")
        if len(text) > max_chars:
            text_preview = text[:max_chars] + "..."
        else:
            text_preview = text

        print(
            f"[{idx:03}] block_id={block_id} "
            f"pages={page_start}-{page_end} "
            f"label={label:<14} "
            f"variant_hint={repr(var_hint)} "
            f"conf={conf:.2f} "
            f"type_hint={repr(type_hint)}"
        )
        print("      ", text_preview)
        print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Inspect block-first full_report.json from inspect_pdf.py"
    )
    parser.add_argument("report", type=str, help="Path to *.full_report.json")
    parser.add_argument(
        "-l",
        "--label",
        action="append",
        help=(
            "Filter by label (can be used multiple times), e.g. "
            "-l variant_header -l variant_body"
        ),
    )
    parser.add_argument(
        "--max-chars",
        type=int,
        default=200,
        help="Max characters for text preview (default: 200)",
    )
    args = parser.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        raise SystemExit(f"Report not found: {report_path}")

    report = load_report(report_path)
    print_summary(report)
    print_blocks(report, labels=args.label, max_chars=args.max_chars)


if __name__ == "__main__":
    main()
